import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it, vi } from 'vitest';
import { z } from 'zod';
import {
  generateConfigCode,
  generateDrizzleConfig,
  generateSchemaCode,
} from '../../src/drizzle/config';
import {
  classifyZodColumn,
  normalizePrimaryKey,
  unwrapZodType,
} from '../../src/drizzle/utils';
import { createSettingsDef, defineStore, defineTable } from '../../src/store';

// ─── generateSchemaCode — column type mapping ─────────────────────────────────

describe('generateSchemaCode — column mapping', () => {
  const AllTypesSchema = z.object({
    id: z.string(),
    count: z.number().int(),
    score: z.number(),
    active: z.boolean(),
    createdAt: z.date(),
    status: z.enum(['a', 'b']),
    nickname: z.string().optional(),
    bio: z.string().nullable(),
    tag: z.string().default('none'),
  });

  const defs = defineStore({
    items: defineTable({
      tableName: 'items',
      schema: AllTypesSchema,
      primaryKey: 'id',
    }),
  });

  const code = generateSchemaCode(defs);

  it('includes the auto-generated header', () => {
    expect(code).toContain('// Auto-generated by @inntend/store');
  });

  it('imports only the column functions that are used', () => {
    expect(code).toContain('import {');
    expect(code).toContain('integer');
    expect(code).toContain('primaryKey');
    expect(code).toContain('real');
    expect(code).toContain('sqliteTable');
    expect(code).toContain('text');
    // index/unique not used here
    expect(code).not.toContain("'index'");
  });

  it('maps z.string() → text().notNull()', () => {
    expect(code).toContain("id: text('id').notNull()");
  });

  it('maps z.number().int() → integer().notNull()', () => {
    expect(code).toContain("count: integer('count').notNull()");
  });

  it('maps z.number() → real().notNull()', () => {
    expect(code).toContain("score: real('score').notNull()");
  });

  it('maps z.boolean() → integer({ mode: boolean }).notNull()', () => {
    expect(code).toContain(
      "active: integer('active', { mode: 'boolean' }).notNull()",
    );
  });

  it('maps z.date() → integer({ mode: timestamp_ms }).notNull()', () => {
    expect(code).toContain(
      "createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull()",
    );
  });

  it('maps z.enum() → text().notNull()', () => {
    expect(code).toContain("status: text('status').notNull()");
  });

  it('optional field → no .notNull()', () => {
    expect(code).toContain("nickname: text('nickname')");
    expect(code).not.toContain("nickname: text('nickname').notNull()");
  });

  it('nullable field → no .notNull()', () => {
    expect(code).toContain("bio: text('bio')");
    expect(code).not.toContain("bio: text('bio').notNull()");
  });

  it('field with .default() → .notNull().default(value)', () => {
    expect(code).toContain(`tag: text('tag').notNull().default("none")`);
  });
});

// ─── generateSchemaCode — z.object() JSON field ──────────────────────────────

describe('generateSchemaCode — z.object() JSON field', () => {
  const defs = defineStore({
    items: defineTable({
      tableName: 'items',
      schema: z.object({
        id: z.string(),
        meta: z.object({ label: z.string(), count: z.number() }),
        tags: z.object({ list: z.array(z.string()) }).optional(),
      }),
      primaryKey: 'id',
    }),
  });
  const code = generateSchemaCode(defs, { settings: false });

  it("maps z.object() → text('field', { mode: 'json' }).notNull()", () => {
    expect(code).toContain("meta: text('meta', { mode: 'json' }).notNull()");
  });

  it("maps z.object().optional() → text('field', { mode: 'json' }) (no notNull)", () => {
    expect(code).toContain("tags: text('tags', { mode: 'json' })");
    expect(code).not.toContain(
      "tags: text('tags', { mode: 'json' }).notNull()",
    );
  });

  it('includes text in imports', () => {
    expect(code).toContain('text');
  });

  it('throws when indexing a JSON field', () => {
    const badDefs = defineStore({
      items: defineTable({
        tableName: 'items',
        schema: z.object({ id: z.string(), meta: z.object({ x: z.number() }) }),
        primaryKey: 'id',
        indexes: [{ columns: ['meta'] }],
      }),
    });
    expect(() => generateSchemaCode(badDefs, { settings: false })).toThrow(
      /cannot index JSON field/,
    );
  });
});

// ─── generateSchemaCode — z.int() and defaults ───────────────────────────────

describe('generateSchemaCode — z.int() and defaults', () => {
  const defs = defineStore({
    t: defineTable({
      tableName: 't',
      schema: z.object({
        id: z.string(),
        mv: z.int().default(0),
        ev: z.int().default(5),
        score: z.number().default(3.14),
        label: z.string().default('none'),
        active: z.boolean().default(false),
        pinned: z.boolean().default(true),
        noDefault: z.string(),
      }),
      primaryKey: 'id',
    }),
  });
  const code = generateSchemaCode(defs);

  it('maps z.int() → integer().notNull()', () => {
    expect(code).toContain("noDefault: text('noDefault').notNull()");
    expect(code).not.toContain(
      "noDefault: text('noDefault').notNull().default(",
    );
  });

  it('z.int().default(0) → integer().notNull().default(0)', () => {
    expect(code).toContain("mv: integer('mv').notNull().default(0)");
  });

  it('z.int().default(5) → integer().notNull().default(5)', () => {
    expect(code).toContain("ev: integer('ev').notNull().default(5)");
  });

  it('z.number().default(3.14) → real().notNull().default(3.14)', () => {
    expect(code).toContain("score: real('score').notNull().default(3.14)");
  });

  it('z.string().default("none") → text().notNull().default("none")', () => {
    expect(code).toContain(`label: text('label').notNull().default("none")`);
  });

  it('z.boolean().default(false) → integer({ mode: boolean }).notNull().default(false)', () => {
    expect(code).toContain(
      "active: integer('active', { mode: 'boolean' }).notNull().default(false)",
    );
  });

  it('z.boolean().default(true) → integer({ mode: boolean }).notNull().default(true)', () => {
    expect(code).toContain(
      "pinned: integer('pinned', { mode: 'boolean' }).notNull().default(true)",
    );
  });
});

// ─── generateSchemaCode — primary key + indexes ───────────────────────────────

describe('generateSchemaCode — primary key and indexes', () => {
  it('single PK in extras block', () => {
    const defs = defineStore({
      users: defineTable({
        tableName: 'users',
        schema: z.object({ id: z.string(), name: z.string() }),
        primaryKey: 'id',
      }),
    });
    const code = generateSchemaCode(defs);
    expect(code).toContain('primaryKey({ columns: [t.id] })');
  });

  it('composite PK lists all fields', () => {
    const defs = defineStore({
      tags: defineTable({
        tableName: 'tags',
        schema: z.object({ userId: z.string(), tag: z.string() }),
        primaryKey: ['userId', 'tag'],
      }),
    });
    const code = generateSchemaCode(defs);
    expect(code).toContain('primaryKey({ columns: [t.userId, t.tag] })');
  });

  it('non-unique index uses index()', () => {
    const defs = defineStore({
      users: defineTable({
        tableName: 'users',
        schema: z.object({ id: z.string(), age: z.number().int() }),
        primaryKey: 'id',
        indexes: [{ columns: ['age'] }],
      }),
    });
    const code = generateSchemaCode(defs);
    expect(code).toContain("index('users_age_idx').on(t.age)");
    expect(code).toContain('import {');
    expect(code).toContain('index');
  });

  it('unique index uses unique()', () => {
    const defs = defineStore({
      users: defineTable({
        tableName: 'users',
        schema: z.object({ id: z.string(), email: z.string() }),
        primaryKey: 'id',
        indexes: [{ columns: ['email'], unique: true }],
      }),
    });
    const code = generateSchemaCode(defs);
    expect(code).toContain("unique('users_email_idx').on(t.email)");
  });

  it('named index uses the provided name', () => {
    const defs = defineStore({
      users: defineTable({
        tableName: 'users',
        schema: z.object({ id: z.string(), email: z.string() }),
        primaryKey: 'id',
        indexes: [{ columns: ['email'], name: 'my_email_idx' }],
      }),
    });
    const code = generateSchemaCode(defs);
    expect(code).toContain("index('my_email_idx').on(t.email)");
  });

  it('compound index joins columns with comma', () => {
    const defs = defineStore({
      posts: defineTable({
        tableName: 'posts',
        schema: z.object({
          id: z.string(),
          userId: z.string(),
          status: z.string(),
        }),
        primaryKey: 'id',
        indexes: [{ columns: ['userId', 'status'] }],
      }),
    });
    const code = generateSchemaCode(defs);
    expect(code).toContain(
      "index('posts_userId_status_idx').on(t.userId, t.status)",
    );
  });

  it('exports a named const for each table key', () => {
    const defs = defineStore({
      users: defineTable({
        tableName: 'users',
        schema: z.object({ id: z.string() }),
        primaryKey: 'id',
      }),
      posts: defineTable({
        tableName: 'posts',
        schema: z.object({ id: z.string() }),
        primaryKey: 'id',
      }),
    });
    const code = generateSchemaCode(defs);
    expect(code).toContain("export const users = sqliteTable('users'");
    expect(code).toContain("export const posts = sqliteTable('posts'");
  });

  it('throws for truly unsupported Zod types (e.g. z.never)', () => {
    const defs = defineStore({
      bad: defineTable({
        tableName: 'bad',
        schema: z.object({ id: z.string(), x: z.never() }),
        primaryKey: 'id',
      }),
    });
    expect(() => generateSchemaCode(defs, { settings: false })).toThrow(
      /unsupported Zod type/,
    );
  });
});

// ─── generateSchemaCode — settings option ────────────────────────────────────

describe('generateSchemaCode — settings option', () => {
  const defs = defineStore({
    items: defineTable({
      tableName: 'items',
      schema: z.object({ id: z.string() }),
      primaryKey: 'id',
    }),
  });

  it('includes __store_settings by default', () => {
    const code = generateSchemaCode(defs);
    expect(code).toContain('__store_settings');
  });

  it('excludes __store_settings when settings: false, even if defineStore already injected it', () => {
    const code = generateSchemaCode(defs, { settings: false });
    expect(code).not.toContain('__store_settings');
  });
});

// ─── generateConfigCode ───────────────────────────────────────────────────────

describe('generateConfigCode', () => {
  it('includes the auto-generated header', () => {
    expect(generateConfigCode()).toContain(
      '// Auto-generated by @inntend/store',
    );
  });

  it('uses sensible defaults', () => {
    const code = generateConfigCode();
    expect(code).toContain("'./schema.ts'");
    expect(code).toContain("'./migrations'");
    expect(code).toContain("'sqlite'");
  });

  it('respects provided options', () => {
    const code = generateConfigCode({
      schema: './src/schema.ts',
      out: './migrations',
      dialect: 'postgresql',
      driver: 'durable-sqlite',
    });
    expect(code).toContain("'./src/schema.ts'");
    expect(code).toContain("'./migrations'");
    expect(code).toContain("'postgresql'");
    expect(code).toContain("'durable-sqlite'");
  });

  it('imports defineConfig from drizzle-kit', () => {
    expect(generateConfigCode()).toContain(
      "import { defineConfig } from 'drizzle-kit'",
    );
  });
});

// ─── generateDrizzleConfig — writes two files (lines 198-216) ────────────────

describe('generateDrizzleConfig — writes schema and config files', () => {
  it('writes to explicit paths', () => {
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    const dir = mkdtempSync(join(tmpdir(), 'inntend-store-test-'));
    try {
      const Schema = z.object({ id: z.string(), label: z.string() });
      const defs = defineStore({
        items: defineTable({
          tableName: 'items',
          schema: Schema,
          primaryKey: 'id',
        }),
      });
      generateDrizzleConfig(defs, {
        schemaOut: join(dir, 'schema.ts'),
        configOut: join(dir, 'drizzle.config.ts'),
      });
      expect(readFileSync(join(dir, 'schema.ts'), 'utf8')).toContain(
        'sqliteTable',
      );
      expect(readFileSync(join(dir, 'drizzle.config.ts'), 'utf8')).toContain(
        'defineConfig',
      );
    } finally {
      logSpy.mockRestore();
      rmSync(dir, { recursive: true });
    }
  });

  it('uses default filenames when no options provided (covers ?? fallbacks)', () => {
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    const dir = mkdtempSync(join(tmpdir(), 'inntend-store-defaults-'));
    const origCwd = process.cwd();
    try {
      process.chdir(dir);
      const Schema = z.object({ id: z.string() });
      const defs: Record<string, any> = {
        items: defineTable({
          tableName: 'items',
          schema: Schema,
          primaryKey: 'id',
        }),
        settings: createSettingsDef(),
      };
      generateDrizzleConfig(defs);
      expect(readFileSync(join(dir, 'schema.ts'), 'utf8')).toContain(
        'sqliteTable',
      );
      expect(readFileSync(join(dir, 'drizzle.config.ts'), 'utf8')).toContain(
        'defineConfig',
      );
    } finally {
      logSpy.mockRestore();
      process.chdir(origCwd);
      rmSync(dir, { recursive: true });
    }
  });
});

// ─── utils.ts branch coverage ─────────────────────────────────────────────────

describe('unwrapZodType — branch coverage', () => {
  it('handles a type whose innerType is undefined (line-33 break)', () => {
    const fakeOptional = { _def: { innerType: undefined } };
    Object.defineProperty(fakeOptional, 'constructor', {
      value: { name: 'ZodOptional' },
    });
    const result = unwrapZodType(fakeOptional);
    expect(result.required).toBe(false);
    expect(result.type).toBeUndefined();
  });

  it('handles a type with no constructor name (line-22 ?? "" branch)', () => {
    // Object.create(null) has no prototype so constructor?.name is undefined.
    const noProto = Object.create(null);
    const result = unwrapZodType(noProto);
    // ctor === '' → falls to break immediately; type is returned as-is.
    expect(result.type).toBe(noProto);
    expect(result.required).toBe(true);
  });
});

describe('generateSchemaCode — settings already in defs (line-78 branch)', () => {
  it('uses the caller-supplied settings table when defs already contains it', () => {
    const Schema = z.object({ id: z.string(), label: z.string() });
    const defs: Record<string, any> = {
      items: defineTable({
        tableName: 'items',
        schema: Schema,
        primaryKey: 'id',
      }),
      settings: createSettingsDef(),
    };
    const code = generateSchemaCode(defs);
    expect(code).toContain('sqliteTable');
  });
});

describe('classifyZodColumn — ?? fallback branches', () => {
  it('throws for an unrecognised type, exercising the ?? "" on line 53', () => {
    expect(() => classifyZodColumn('x', null)).toThrow('unsupported Zod type');
  });

  it('classifies ZodNumber with no checks as real (checks ?? [] branch on line 68)', () => {
    const fakeNumber = { constructor: { name: 'ZodNumber' }, _def: {} };
    expect(classifyZodColumn('x', fakeNumber)).toEqual({ tag: 'real' });
  });
});

describe('normalizePrimaryKey — undefined falls back to "id" (line 139)', () => {
  it('returns ["id"] when rawPk is undefined', () => {
    expect(normalizePrimaryKey(undefined)).toEqual(['id']);
  });
});
